version: "3"

services:
  mysql_serve:
    image: mysql:5.6.42
    container_name: db_enviame2
    ports:
      - 33060:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: enviame
      MYSQL_ROOT_PASSWORD: 123456
  web_enviame:
    build: .
    container_name: enviame2
    ports:
      - 8082:80
    volumes:
      - $PWD:/opt/data
    links:
      - mysql_serve
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
