version: "3"

services:
  mysql_serve:
    image: mysql:8.0.18
    container_name: db_enviame1
    ports:
      - 33060:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
  pangacr_web:
    build: .
    container_name: enviame1
    ports:
      - 8009:80
    volumes:
      - $PWD:/opt/data
    links:
      - mysql_serve
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
